# Simplified Cloud Build configuration for deployment
# This version uses a more straightforward approach to secrets

steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/aura-web:$BUILD_ID'
      - '-t'
      - 'gcr.io/$PROJECT_ID/aura-web:latest'
      - '--build-arg'
      - 'NEXT_PUBLIC_SUPABASE_URL=https://ahzmfkjtiiyuipweaktx.supabase.co'
      - '--build-arg'
      - 'NEXT_PUBLIC_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFoem1ma2p0aWl5dWlwd2Vha3R4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2Mzc3OTksImV4cCI6MjA2ODIxMzc5OX0.adTiPqedJv1TvuDvj53HGA_jlZr23MJ_L3jiKDb0GTk'
      - '--build-arg'
      - 'NEXT_PUBLIC_APP_URL=https://aura-dashboard-mn5srfeinq-uc.a.run.app'
      - '--build-arg'
      - 'NEXT_PUBLIC_GOOGLE_CLIENT_ID=205298800820-4l2r0ro2m6lvc73g6id03r4fnbp25m52.apps.googleusercontent.com'
      - '--build-arg'
      - 'NEXT_PUBLIC_MICROSOFT_CLIENT_ID=07a43345-3aa6-4444-8859-c44105e4769d'
      - '--build-arg'
      - 'NEXT_PUBLIC_STRAVA_CLIENT_ID=170903'
      - '--build-arg'
      - 'OPENAI_API_KEY=build-time-placeholder'
      - '--build-arg'
      - 'JWT_SECRET=build-time-placeholder-will-be-replaced-at-runtime'
      - '.'

  # Step 2: Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/aura-web:$BUILD_ID']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/aura-web:latest']

  # Step 3: Deploy to Cloud Run (simplified approach)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - '-c'
      - |
        gcloud run deploy aura-dashboard \
          --image gcr.io/$PROJECT_ID/aura-web:$BUILD_ID \
          --region us-central1 \
          --platform managed \
          --allow-unauthenticated \
          --memory 1Gi \
          --cpu 1 \
          --timeout 300 \
          --max-instances 10 \
          --set-env-vars NEXT_PUBLIC_SUPABASE_URL=https://ahzmfkjtiiyuipweaktx.supabase.co,NEXT_PUBLIC_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFoem1ma2p0aWl5dWlwd2Vha3R4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2Mzc3OTksImV4cCI6MjA2ODIxMzc5OX0.adTiPqedJv1TvuDvj53HGA_jlZr23MJ_L3jiKDb0GTk,NEXT_PUBLIC_GOOGLE_CLIENT_ID=205298800820-4l2r0ro2m6lvc73g6id03r4fnbp25m52.apps.googleusercontent.com,NEXT_PUBLIC_MICROSOFT_CLIENT_ID=07a43345-3aa6-4444-8859-c44105e4769d,NEXT_PUBLIC_STRAVA_CLIENT_ID=170903,NEXT_PUBLIC_APP_URL=https://aura-dashboard-mn5srfeinq-uc.a.run.app,NODE_ENV=production \
          --update-secrets STRIPE_SECRET_KEY=STRIPE_SECRET_KEY:latest,NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=STRIPE_PUBLISHABLE_KEY:latest,STRIPE_WEBHOOK_SECRET=STRIPE_WEBHOOK_SECRET:latest,STRIPE_PERSONAL_PRICE_ID=STRIPE_PERSONAL_PRICE_ID:latest,STRIPE_FAMILY_PRICE_ID=STRIPE_FAMILY_PRICE_ID:latest,STRIPE_BUSINESS_PRICE_ID=STRIPE_BUSINESS_PRICE_ID:latest,OPENAI_API_KEY=OPENAI_API_KEY:latest,JWT_SECRET=JWT_SECRET:latest,SUPABASE_SERVICE_ROLE_KEY=SUPABASE_SERVICE_ROLE_KEY:latest,NEXT_PUBLIC_OPENWEATHER_API_KEY=OPENWEATHER_API_KEY:latest,NEWS_API_KEY=NEWS_API_KEY:latest,GOOGLE_CLIENT_SECRET=GOOGLE_CLIENT_SECRET:latest,MICROSOFT_CLIENT_SECRET=MICROSOFT_CLIENT_SECRET:latest,STRAVA_CLIENT_SECRET=STRAVA_CLIENT_SECRET:latest

# Images to be pushed to Container Registry
images:
  - 'gcr.io/$PROJECT_ID/aura-web:$BUILD_ID'
  - 'gcr.io/$PROJECT_ID/aura-web:latest'

# Build timeout
timeout: '1200s'

# Machine type for the build
options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY