steps:
  # Build dashboard image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-dashboard'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/aura-platform-467500/aura-dashboard:latest'
      - '-f'
      - 'Dockerfile'
      - '--build-arg'
      - 'NEXT_PUBLIC_SUPABASE_URL=${_SUPABASE_URL}'
      - '--build-arg'
      - 'NEXT_PUBLIC_SUPABASE_ANON_KEY=${_SUPABASE_ANON_KEY}'
      - '--build-arg'
      - 'NEXT_PUBLIC_APP_URL=https://app.aura-link.app'
      - '.'

  # Push dashboard image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-dashboard'
    args:
      - 'push'
      - 'gcr.io/aura-platform-467500/aura-dashboard:latest'
    waitFor:
      - 'build-dashboard'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-dashboard'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'aura-dashboard'
      - '--image'
      - 'gcr.io/aura-platform-467500/aura-dashboard:latest'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '3000'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--update-secrets=OPENAI_API_KEY=OPENAI_API_KEY:latest,JWT_SECRET=JWT_SECRET:latest,SUPABASE_SERVICE_ROLE_KEY=SUPABASE_SERVICE_ROLE_KEY:latest,NEXT_PUBLIC_OPENWEATHER_API_KEY=OPENWEATHER_API_KEY:latest,NEWS_API_KEY=NEWS_API_KEY:latest,GOOGLE_CLIENT_SECRET=GOOGLE_CLIENT_SECRET:latest,MICROSOFT_CLIENT_SECRET=MICROSOFT_CLIENT_SECRET:latest,STRAVA_CLIENT_SECRET=STRAVA_CLIENT_SECRET:latest'
      - '--set-env-vars'
      - 'NODE_ENV=production,NEXT_PUBLIC_SUPABASE_URL=${_SUPABASE_URL},NEXT_PUBLIC_SUPABASE_ANON_KEY=${_SUPABASE_ANON_KEY},NEXT_PUBLIC_APP_URL=https://app.aura-link.app,NEXT_PUBLIC_GOOGLE_CLIENT_ID=${_GOOGLE_CLIENT_ID},NEXT_PUBLIC_MICROSOFT_CLIENT_ID=${_MICROSOFT_CLIENT_ID},NEXT_PUBLIC_STRAVA_CLIENT_ID=${_STRAVA_CLIENT_ID}'
      - '--set-secrets'
      - 'STRIPE_SECRET_KEY=projects/aura-platform-467500/secrets/STRIPE_SECRET_KEY/versions/latest,STRIPE_PUBLISHABLE_KEY=projects/aura-platform-467500/secrets/STRIPE_PUBLISHABLE_KEY/versions/latest,STRIPE_WEBHOOK_SECRET=projects/aura-platform-467500/secrets/STRIPE_WEBHOOK_SECRET/versions/latest,STRIPE_PERSONAL_PRICE_ID=projects/aura-platform-467500/secrets/STRIPE_PERSONAL_PRICE_ID/versions/latest,STRIPE_FAMILY_PRICE_ID=projects/aura-platform-467500/secrets/STRIPE_FAMILY_PRICE_ID/versions/latest,STRIPE_BUSINESS_PRICE_ID=projects/aura-platform-467500/secrets/STRIPE_BUSINESS_PRICE_ID/versions/latest'
    waitFor:
      - 'push-dashboard'

options:
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: 100
  logging: CLOUD_LOGGING_ONLY

timeout: 1200s

# Substitutions for build-time variables
substitutions:
  _SUPABASE_URL: 'https://ahzmfkjtiiyuipweaktx.supabase.co'
  _SUPABASE_ANON_KEY: '${SUPABASE_ANON_KEY}' # Will be provided via Cloud Build trigger
  _GOOGLE_CLIENT_ID: '${GOOGLE_CLIENT_ID}' # Will be provided via Cloud Build trigger
  _MICROSOFT_CLIENT_ID: '${MICROSOFT_CLIENT_ID}' # Will be provided via Cloud Build trigger
  _STRAVA_CLIENT_ID: '${STRAVA_CLIENT_ID}' # Will be provided via Cloud Build trigger