# Cloud Build configuration for Aura Platform
# This file builds and deploys the web application to Cloud Run

steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/aura-web:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/aura-web:latest'
      - '--build-arg'
      - 'NEXT_PUBLIC_SUPABASE_URL=https://ahzmfkjtiiyuipweaktx.supabase.co'
      - '--build-arg'
      - 'NEXT_PUBLIC_SUPABASE_ANON_KEY=${_SUPABASE_ANON_KEY}'
      - '--build-arg'
      - 'NEXT_PUBLIC_APP_URL=https://aura-dashboard-mn5srfeinq-uc.a.run.app'
      - '--build-arg'
      - 'NEXT_PUBLIC_GOOGLE_CLIENT_ID=${_GOOGLE_CLIENT_ID}'
      - '--build-arg'
      - 'NEXT_PUBLIC_MICROSOFT_CLIENT_ID=${_MICROSOFT_CLIENT_ID}'
      - '--build-arg'
      - 'NEXT_PUBLIC_STRAVA_CLIENT_ID=${_STRAVA_CLIENT_ID}'
      
      - '--build-arg'
      - 'OPENAI_API_KEY=build-time-placeholder'
      - '--build-arg'
      - 'JWT_SECRET=build-time-placeholder-will-be-replaced-at-runtime'
      - '.'

  # Step 2: Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/aura-web:$COMMIT_SHA']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/aura-web:latest']

  # Step 3: Deploy to Cloud Run with all secrets
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'aura-dashboard'
      - '--image'
      - 'gcr.io/$PROJECT_ID/aura-web:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--timeout'
      - '300'
      - '--max-instances'
      - '10'
      - '--update-secrets'
      - 'STRIPE_SECRET_KEY=STRIPE_SECRET_KEY:latest'
      - '--update-secrets'
      - 'NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=STRIPE_PUBLISHABLE_KEY:latest'
      - '--update-secrets'
      - 'STRIPE_WEBHOOK_SECRET=STRIPE_WEBHOOK_SECRET:latest'
      - '--update-secrets'
      - 'STRIPE_PERSONAL_PRICE_ID=STRIPE_PERSONAL_PRICE_ID:latest'
      - '--update-secrets'
      - 'STRIPE_FAMILY_PRICE_ID=STRIPE_FAMILY_PRICE_ID:latest'
      - '--update-secrets'
      - 'STRIPE_BUSINESS_PRICE_ID=STRIPE_BUSINESS_PRICE_ID:latest'
      - '--update-secrets'
      - 'OPENAI_API_KEY=OPENAI_API_KEY:latest'
      - '--update-secrets'
      - 'JWT_SECRET=JWT_SECRET:latest'
      - '--update-secrets'
      - 'SUPABASE_SERVICE_ROLE_KEY=SUPABASE_SERVICE_ROLE_KEY:latest'
      - '--update-secrets'
      - 'OPENWEATHER_API_KEY=OPENWEATHER_API_KEY:latest'
      
      - '--update-secrets'
      - 'NEWS_API_KEY=NEWS_API_KEY:latest'
      - '--update-secrets'
      - 'GOOGLE_CLIENT_SECRET=GOOGLE_CLIENT_SECRET:latest'
      - '--update-secrets'
      - 'MICROSOFT_CLIENT_SECRET=MICROSOFT_CLIENT_SECRET:latest'
      - '--update-secrets'
      - 'STRAVA_CLIENT_SECRET=STRAVA_CLIENT_SECRET:latest'
      - '--set-env-vars'
      - 'NEXT_PUBLIC_SUPABASE_URL=https://ahzmfkjtiiyuipweaktx.supabase.co'
      - '--set-env-vars'
      - 'NEXT_PUBLIC_SUPABASE_ANON_KEY=${_SUPABASE_ANON_KEY}'
      - '--set-env-vars'
      - 'NEXT_PUBLIC_GOOGLE_CLIENT_ID=${_GOOGLE_CLIENT_ID}'
      - '--set-env-vars'
      - 'NEXT_PUBLIC_MICROSOFT_CLIENT_ID=${_MICROSOFT_CLIENT_ID}'
      - '--set-env-vars'
      - 'NEXT_PUBLIC_STRAVA_CLIENT_ID=${_STRAVA_CLIENT_ID}'
      - '--set-env-vars'
      - 'NEXT_PUBLIC_APP_URL=https://aura-dashboard-mn5srfeinq-uc.a.run.app'
      - '--set-env-vars'
      - 'NODE_ENV=production'

# Images to be pushed to Container Registry
images:
  - 'gcr.io/$PROJECT_ID/aura-web:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/aura-web:latest'

# Build timeout
timeout: '1200s'

# Machine type for the build
options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY