# Google Cloud Build configuration for Aura Platform
steps:
  # Build and push the dashboard/web application
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/aura-dashboard:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/aura-dashboard:latest'
      - '-f'
      - 'Dockerfile.web'
      - '--build-arg'
      - 'NEXT_PUBLIC_SUPABASE_URL=https://ahzmfkjtiiyuipweaktx.supabase.co'
      - '--build-arg'
      - 'NEXT_PUBLIC_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFoem1ma2p0aWl5dWlwd2Vha3R4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2Mzc3OTksImV4cCI6MjA2ODIxMzc5OX0.adTiPqedJv1TvuDvj53HGA_jlZr23MJ_L3jiKDb0GTk'
      - '.'
    id: 'build-dashboard'

  # Marketing app deployment disabled - using web app for both domains
  # - name: 'gcr.io/cloud-builders/docker'
  #   args:
  #     - 'build'
  #     - '-t'
  #     - 'gcr.io/$PROJECT_ID/aura-marketing:$COMMIT_SHA'
  #     - '-t'
  #     - 'gcr.io/$PROJECT_ID/aura-marketing:latest'
  #     - '-f'
  #     - 'Dockerfile.marketing'
  #     - '--build-arg'
  #     - 'NEXT_PUBLIC_DASHBOARD_URL=https://app.aura-link.app'
  #     - '.'
  #   id: 'build-marketing'

  # Push dashboard image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/aura-dashboard:$COMMIT_SHA'
    waitFor: ['build-dashboard']
    id: 'push-dashboard-sha'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/aura-dashboard:latest'
    waitFor: ['build-dashboard']
    id: 'push-dashboard-latest'

  # Push marketing image - disabled
  # - name: 'gcr.io/cloud-builders/docker'
  #   args:
  #     - 'push'
  #     - 'gcr.io/$PROJECT_ID/aura-marketing:$COMMIT_SHA'
  #   waitFor: ['build-marketing']
  #   id: 'push-marketing-sha'

  # - name: 'gcr.io/cloud-builders/docker'
  #   args:
  #     - 'push'
  #     - 'gcr.io/$PROJECT_ID/aura-marketing:latest'
  #   waitFor: ['build-marketing']
  #   id: 'push-marketing-latest'

  # Deploy dashboard to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'aura-dashboard'
      - '--image'
      - 'gcr.io/$PROJECT_ID/aura-dashboard:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '3000'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
    waitFor: ['push-dashboard-sha']

  # Deploy marketing to Cloud Run - disabled, using web app for both domains
  # - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  #   entrypoint: 'gcloud'
  #   args:
  #     - 'run'
  #     - 'deploy'
  #     - 'aura-marketing'
  #     - '--image'
  #     - 'gcr.io/$PROJECT_ID/aura-marketing:$COMMIT_SHA'
  #     - '--region'
  #     - 'us-central1'
  #     - '--platform'
  #     - 'managed'
  #     - '--allow-unauthenticated'
  #     - '--port'
  #     - '3000'
  #     - '--memory'
  #     - '512Mi'
  #     - '--cpu'
  #     - '1'
  #     - '--min-instances'
  #     - '0'
  #     - '--max-instances'
  #     - '5'
  #     - '--set-env-vars'
  #     - 'NODE_ENV=production,NEXT_PUBLIC_DASHBOARD_URL=https://app.aura-link.app'
  #   waitFor: ['push-marketing-sha']

# Store images in Google Container Registry
images:
  - 'gcr.io/$PROJECT_ID/aura-dashboard:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/aura-dashboard:latest'
  # Marketing images disabled - using web app for both domains
  # - 'gcr.io/$PROJECT_ID/aura-marketing:$COMMIT_SHA'
  # - 'gcr.io/$PROJECT_ID/aura-marketing:latest'

# Build configuration
options:
  machineType: 'E2_HIGHCPU_32'
  diskSizeGb: 100
  logging: CLOUD_LOGGING_ONLY

# Timeout for the entire build
timeout: '1200s'